openapi: 3.0.0
info:
  title: RAG Chatbot API for Physical AI & Humanoid Robotics Book
  description: API for querying the robotics book content using Retrieval-Augmented Generation
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Local development server
  - url: https://your-deployed-api.com
    description: Production server

paths:
  /api/query:
    post:
      summary: Query the robotics book content
      description: Submit a question about humanoid robotics and get a response based on the book content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - question
              properties:
                question:
                  type: string
                  description: The question about humanoid robotics
                  example: "Explain how ROS 2 nodes communicate with each other"
                max_tokens:
                  type: integer
                  description: Maximum number of tokens in the response
                  default: 500
                temperature:
                  type: number
                  description: Controls randomness in the response
                  default: 0.7
                  minimum: 0
                  maximum: 1
      responses:
        '200':
          description: Successful response to the query
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                    description: The answer to the question based on book content
                  sources:
                    type: array
                    items:
                      type: object
                      properties:
                        module:
                          type: string
                          description: The module where the information was found
                        chapter:
                          type: string
                          description: The chapter where the information was found
                        text:
                          type: string
                          description: The relevant text snippet
                        similarity_score:
                          type: number
                          description: Similarity score of the retrieved content
                    description: List of sources used to generate the answer
                  citations:
                    type: array
                    items:
                      type: string
                    description: Academic or official citations referenced in the answer
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message

  /api/index:
    post:
      summary: Index book content
      description: Add or update the book content in the vector database for RAG
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  description: The content to be indexed
                module:
                  type: string
                  description: The module this content belongs to
                chapter:
                  type: string
                  description: The chapter this content belongs to
                chunk_size:
                  type: integer
                  description: Size of content chunks for indexing
                  default: 750
      responses:
        '200':
          description: Content successfully indexed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success message
                  indexed_chunks:
                    type: integer
                    description: Number of chunks indexed
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message

  /api/validate:
    get:
      summary: Validate RAG system
      description: Check if the RAG system is properly configured and working
      responses:
        '200':
          description: System is valid and working
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: System status
                  vector_db_connected:
                    type: boolean
                    description: Whether vector database is connected
                  content_indexed:
                    type: boolean
                    description: Whether content has been indexed
                  last_indexed:
                    type: string
                    format: date-time
                    description: When content was last indexed